### ISSUE TITLE
Doesn't work when watching

### ISSUE THREAD

**Issue by strarsis** [Log1x/blade-svg-sage#15]
When using watch in sage9 theme using `yarn start`, the production assets in `dist/` are cleaned up, 
hence `blade-svg-sage` can't find the SVGs and the page fails to load.
How can it be configured to look for the SVGs in assets directory instead?

I have to use this workaround while watching:
```php
add_filter('bladesvg_image_path', function () {
    return '/srv/www/web/app/themes/the-theme/resources/assets/images/svg/icon';
});
````

**Comment by strarsis** [comment]
@Log1x: Related roots discourse discussion: https://discourse.roots.io/t/asset-lookup-while-watching/12640

**Comment by Log1x** [comment]
I'm going to rewrite and fix a lot of these issues here shortly as I plan on using this in a project I'm currently working on.

I think it went in the wrong direction with a couple of the recent commits. There are a few things to consider:

1. I merged a commit making it check the manifest for the final file name, but really; an SVG that's being read from the filesystem doesn't need to be cache busted.
2. I'm unsure if we should read the SVG from `dist` or keep it defaulted to `assets` since, like the above, it's being read by the file system. At that point, it'd come down to if the `assets` folder is being pushed to the production server or not. But related to the roots discourse discussion above, whether the SVG's should actually live with the other assets while being used inline, is another point that needs to be addressed.

**Comment by Log1x** [comment]
[v2.0.0](https://github.com/Log1x/blade-svg-sage/pull/16) will take care of this.
