### ISSUE TITLE
Hassed assets names on production

### ISSUE THREAD

**Issue by aitormendez** [Log1x/blade-svg-sage#18]
I'm getting the `File does not exist at path` error when `yarn build:production`.

This is the warning: 

`File does not exist at path /srv/www/margenesdelarte.org/current/web/app/themes/mrg/dist/images/svg/flecha-aba-peq.svg`

I've seen older issues with the same error that seems to be fixed but I'm getting this error with a fresh install of Sage and blade-svg-sage.

**Comment by Log1x** [comment]
Are you sure it's installing [v2.0.0](https://github.com/Log1x/blade-svg-sage/releases/tag/v2.0.0)? The default path was changed to `resources/svg` is why I ask.

**Comment by aitormendez** [comment]
https://github.com/aitormendez/margenesdelarte/blob/c2e961db04213833210ef4a781e869a62b22780d/web/app/themes/mrg/composer.json#L40

**Comment by aitormendez** [comment]
I've changed the default path:

https://github.com/aitormendez/margenesdelarte/blob/c2e961db04213833210ef4a781e869a62b22780d/web/app/themes/mrg/app/filters.php#L98-L107

**Comment by Log1x** [comment]
Sorry about the delayed response.

The reason your path isn't working is due to how Sage's default webpack config hashes the filename. During compilation, `flecha-aba-peq.svg` would become `flecha-aba-peq_[hash].svg` which is ultimately why I moved away from using the `dist` directory as it's not necessary to hash (especially in the way Sage does it out of the box) something you're programmatically inlining in your markup.

When I get some time, I will look into implementing a config variable that you can set to `true` to make Blade SVG use the manifest (`asset_path()`) for retrieving the SVG– but I can't give an ETA or even a promise that it will happen due to how blade-svg handles pathing internally:

- We call `SvgFactory()->svg($name)` (e.g. `@svg('name')`) from [SvgFactory.php#L68](https://github.com/adamwathan/blade-svg/blob/master/src/SvgFactory.php#L68).
- It initializes the Svg class with our icon name and default render mode (inline).
- It uses `Svg()->renderInline()` from [Svg.php#L54](https://github.com/adamwathan/blade-svg/blob/master/src/Svg.php#L54) which then goes back to SvgFactory to call [`SvgFactory()->getSvg($name)`](https://github.com/adamwathan/blade-svg/blob/master/src/SvgFactory.php#L105) of which finally combines the path and icon.

This ends up making it difficult to alter the icon/path and wrap it in `asset_path()` to make us able to return the value from the manifest.json.

But if I'm being honest, this all comes down to Sage's build system being way over the top in handling cache busting. It should instead do what Laravel Mix and every other build system does, and append an argument to the end of the filename inside of the manifest on each build such as `icon.svg?id=[hash]` so pulling an asset from the manifest isn't forcefully required.

So ultimately, your options as of right now are:

- Keep them in `resources/` like my default config.
- Change out Sage 9's build system for Laravel Mix (which is what I personally do even when not using this package.)

**Comment by aitormendez** [comment]
Understood. Thank you for your time and your excelent work.
